### PR TITLE
Fix for get_playlist() with more than 1000 tracks

### PR DESCRIPTION
**Pull request by alkk**
#25 was reintroduced at some point

### CODE REVIEW

**Comment by alkk** [comment]
I was testing 6b51e11 with python 3.8.5 (from brew) on macOS.
Youtube Music language is set to "English (US)", if it matters.

Locale:
```
(ytmusic) ➜ ytmusic git:(master) python
Python 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale()
('en_US', 'UTF-8')
>>> 
```

Test code:
```python
#!/usr/bin/env python3

from ytmusicapi import YTMusic

m = YTMusic('headers_auth.json')
for playlist in m.get_library_playlists():
	playlist_with_tracks = m.get_playlist(playlist['playlistId'], 50000)
```

Exception:
```Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    playlist_with_tracks = m.get_playlist(playlist['playlistId'], 50000)
  File "/Users/alk/.virtualenvs/ytmusic/lib/python3.8/site-packages/ytmusicapi-0.9.1-py3.8.egg/ytmusicapi/mixins/playlists.py", line 88, in get_playlist
    song_count = to_int(
  File "/Users/alk/.virtualenvs/ytmusic/lib/python3.8/site-packages/ytmusicapi-0.9.1-py3.8.egg/ytmusicapi/helpers.py", line 55, in to_int
    return locale.atoi(number)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/locale.py", line 330, in atoi
    return int(delocalize(string))
ValueError: invalid literal for int() with base 10: '5,000'
```

**Comment by sigma67** [comment]
It seems you're using MacOS, so it's probably an issue specific to Mac. Unfortunately I don't have a Mac to reproduce this. 

I assume there's an issue setting the locale, but you can't see it because it's being suppressed. In your local installation, can you remove the ``with suppress(locale.Error)`` in l.83 of ytmusic.py to see if you're getting a loCALE error? 

Another thing you could try is replace ``en_US.UTF-8`` in l.84 with ``EN_US``, which seems to be the default locale on MacOS (see here: https://stackoverflow.com/a/49141383/5726546). If that turns out to be the cause, we can implement a Mac specific locale like this:

```python
import platform
if (platform.system() == 'Darwin'): 
    locale.setlocale(locale.LC_ALL, 'EN_US')
```

**Comment by alkk** [comment]
Looks like problem is with "en_US.UTF8", it should be "en_US.UTF-8".
Python on Linux (and maybe Windows) accept "en_US.UTF8", but on mac is fails.

macOS:
```
(ytmusic) ➜ ytmusic git:(master) python3
Python 3.8.5 (default, Jul 21 2020, 10:48:26) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(locale.LC_ALL, 'en_US.UTF8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
>>> locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
'en_US.UTF-8'
>>> 
(ytmusic) ➜ ytmusic git:(master) locale -a|grep en_US
en_US.US-ASCII
en_US.UTF-8
en_US
en_US.ISO8859-15
en_US.ISO8859-1
```

Debian 9 (with default locale set to en_US.UTF-8):
```
alk@aldebaran:~$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
alk@aldebaran:~$ python3
Python 3.5.3 (default, Jul  9 2020, 13:00:10) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(locale.LC_ALL, 'en_US.UTF8')
'en_US.UTF8'
>>> locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
'en_US.UTF-8'
>>> 
alk@aldebaran:~$ locale -a|grep en_US
en_US.utf8
```

**Comment by sigma67** [comment]
Wonderful, I overlooked that little spelling difference. Merged in 6a979ad.

Unfortunately commit id changed due to rebase, so it's not marked as merged, but your name still shows up on the contributors list.

**Pull request closed without merging**
