### PR TITLE
Add radio/Shuffle ID to search results

### PR DESCRIPTION
**Pull request by PhracturedBlue**
I wanted to be able to create streaming radio channels from search results.
This patch extracts the Shuffle and Radio playlist ids from the search results.

yapf seems to have changed an unrelated line for some reason, I can manually revert it if you like

I was unable to get all the tests to pass (even without my change), but the search tests all seem to work ok

### CODE REVIEW

**Comment by sigma67** [comment]
I really like this idea, I think we could add this code across the board. Most endpoints actually have these menu entries and it shouldn't break any existing functionality.

**Comment by sigma67** [comment]
As you suggested in a comment, we should definitely use the iconType to determine the correct menu item. The text which is used now is sensitive to localization ("hl" setting in headers). Feel free to update the PR accordingly.

**Comment by PhracturedBlue** [comment]
I have updated the pattern to use the icon name which is hopefully more robust to locales.

**Comment by sigma67** [comment]
Thanks for the update. I experimented a bit more and found that getting the shuffle id is pointless. It's always the same as the playlist id. Instead you should call `get_watch_playlist_shuffle` with the playlist id, that's what happens behind the scenes when you press shuffle. Difference to normal play is that it only adds the hard coded param `wAEB8gECGAE%3D`, which is always the same for any type of shuffle.

**Comment by sigma67** [comment]
I think we should go ahead and implement shuffle/radio ID for artist results only. 

For all others, I will create a new top level docs page that includes info on intricacies of the YTMusic API, which would include the composition of radio IDs. Should be very helpful to new developers.

**Comment by PhracturedBlue** [comment]
I was primarily just concerned with artist, so that makes sense.

**Pull request closed without merging**
