### PR TITLE
fix(playlists): handle missing regex group in trackCount

### LINKED ISSUE #650: Incorrect track count for playlists with 1000+ songs
Hello all,

This is an issue with the regex in the playlist mixin. It causes only the first group to be returned. For example if the playlist had `3647` songs it would return `3` due to how `re.search(r"\d+", song_count_text)` is used.

**To Reproduce**
1. Find a playlist with 1000+ songs
2. Use the `YTMusic.get_playlist()` function
3. Print the `trackCount` object.
4. It should return only the first digit

**Additional context**
```python
from ytmusicapi import YTMusic

# Initialize YouTube Music API
ytmusic = YTMusic()

PLAYLIST_ID = "XXXXXX"

# Call get_playlist
playlist = ytmusic.get_playlist(PLAYLIST_ID)

#Print trackCount to the console
print(playlist["trackCount"])
```

### PR DESCRIPTION
**Pull request by RealCalumPlays**
Fixes #650

### CODE REVIEW

**Comment by sigma67** [comment]
Hi @RealCalumPlays , thanks for your contribution. Could you please add a test that covers this case? Best to use a public playlist with 1000+ entries.

**Comment by RealCalumPlays** [comment]
Yup can do that for ya. Sorry for the late response. Do you want another PR when I have added it?

**Comment by sigma67** [comment]
@RealCalumPlays Thanks! No, just add it here. Please add it next to the existing tests for `get_playlist`. Since it's a public playlist you shouldn't have to bother with the configuration setup I hope.

**Comment by RealCalumPlays** [comment]
Okay I have just added it to `TestPlaylists::test_get_playlist_foreign_new_format` and `TestPlaylists::test_get_playlist_foreign` (I think thats the place you wanted me to do it?) I have also updated the first playlist ID used in the first check in those functions as they do not work anymore causing the tests to always fail.

**Comment by sigma67** [comment]
@RealCalumPlays Thanks! Quality playlist choice. I'll have a look

**Pull request merged**
