### PR TITLE
Update parsers.py

### PR DESCRIPTION
**Pull request by joshc0**
Ran into an error where the playlist data didn't have a 'title' 
- Added a check if title exists

### CODE REVIEW

**Comment by sigma67** [comment]
Can you provide an example playlist where this error occurs with the latest commit?

**Comment by joshc0** [comment]
I had a playlist that didn't have a title, I think from migrating from
Google Play music

**Comment by sigma67** [comment]
Could you make that playlist public and post a link here? Otherwise I can't reproduce

**Comment by joshc0** [comment]
Yep will do

**Comment by joshc0** [comment]
Hmm, I can't edit the permissions to make it public without giving it a
title... Happy to just delete the playlist and kill the commit

**Comment by sigma67** [comment]
Yea I think this is just an edge case with the migration that they need to fix, since you can't actually create playlists with empty titles in YTMusic itself. Should probably submit to Google support. 

Nevertheless, you're welcome to submit pull requests again in the future!

**Comment by joshc0** [comment]
Ah, I figured out how to do it, in case it comes up again,
https://music.youtube.com/playlist?list=PLtZPdV7nmt41QW-H01PRypm3CpExx7DUa

**Pull request closed without merging**
