### PR TITLE
🎉 Added get_lyrics method to get lyrics of a video or song

### PR DESCRIPTION
**Pull request by alexmercerind**
I always felt requirement of getting lyrics of songs with this library, so I added it.
Now, ```get_lyrics``` in ```BrowsingMixin``` class can be used to get lyrics of a video or song.

**Script**
```py
import json
from ytmusicapi import YTMusic

ytMusic = YTMusic()
result = ytMusic.get_lyrics('LFJIxKC1tBc')
print(json.dumps(result, indent = 4))
```
**Result**
```json
{
    "videoId": "LFJIxKC1tBc",
    "browseId": "MPLYt_3qQDfDjDB7j-2",
    "lyricsFound": true,
    "lyrics": "Why's it so hard to look me in the eye?\r\nPlaying with that cross that's on your chain\r\nI know you only ever bite your lip\r\nWhen it's something you're afraid to say\r\n\r\nIs this the last time that I lay my eyes upon you?\r\nIs this the last time that I ever watch you leave?\r\nThis is the last thing I would ever have done to ya\r\nThis is the last thing that I thought you'd do to me\r\n\r\nWe said that it would last, but how come it's the last time?\r\nI'm tryna hold your hand but feeling like my hand's tied\r\nYou said we'd be forever, now you never ever be mine (oh-oh-oh)\r\nYou said that it would last, but how come it's the last time?\r\n\r\nYou practiced leaving many times before\r\nBut I guess you get it right today\r\nLeaving that ring I gave you in the drawer\r\nBut you taking every single part of me\r\n\r\nIs this the last time that I lay my eyes upon you?\r\nIs this the last time that I ever watch you leave?\r\nThis is the last thing I would ever have done to ya\r\nThis is the last thing that I thought you'd do to me\r\n\r\nWe said that it would last, but how come it's the last time? (Oh-oh-oh)\r\nI'm tryna hold your hand but feeling like my hand's tied (oh-oh-oh)\r\nYou said we'd be forever, now you never ever be mine (oh-oh-oh)\r\nYou said that it would last, but how come it's the last time? Oh (oh-oh-oh)\r\n\r\nI think of the first kiss \r\nThat lead to the first night\r\nWhoa, whoa\r\nI think of the first tiff\r\nThat lead to the first fight\r\nWhoa, whoa\r\nOoh\r\n\r\nYou said that it would last, but how come it's the last time?\r\nI'm tryna hold your hand but feeling like my hand's tied, mm (oh-oh-oh)\r\nWe always said we'd be forever, now you never ever be mine, ooh (oh-oh-oh)\r\nWe said that it would last, but how come it's the last time? Oh, ooh (oh-oh-oh)\r\n\r\nI think of the first kiss\r\nThat lead to the first night\r\nWhoa (first night), whoa (whoa)\r\nI think of the first tiff (the first tiff)\r\nThat lead to the first fight\r\nWhoa, whoa, oh\r\n\r\nYou said that it would last, but how come it's the last time?",
    "source": "Source: LyricFind"
}
```

I also added docstring with suitable example (using same video ID as you used for other docstrings).

Please merge 💙!
Thankyou 🍀!

Please let me know if you need any change in the code 😉.
I believe the changes in this PR are completely apart from your other code, so you're not going to experience any conflicts or any breaking problems.

### CODE REVIEW

**Comment by sigma67** [comment]
Great idea! What happens if there are no lyrics?

**Comment by alexmercerind** [comment]
Hello @sigma67!
Now the songs or videos which do not have lyrics will give such return:
```json
{
    "videoId": "0Ie6OIvq33E",
    "browseId": "MPLYt_b2D8HLA8KTJ-3",
    "lyrics": "If the song has lyrics, they'll show up here when they become available",
    "source": "Lyrics not available"
}
```

Everything seems fine to me now.
I also added lyrics' source along the way.

**Comment by sigma67** [comment]
Looks good. Can you also write a test that covers both lyrics/no lyrics cases?

**Comment by alexmercerind** [comment]
@sigma67. Is that alright?

I just added assertion for None. As default value of all the keys in the dictionary is None, & if everything goes well, then their value won't be None.

**Comment by raitonoberu** [comment]
I think we should just return None if the lyrics are not found:
```
{
    "videoId": "0Ie6OIvq33E",
    "browseId": "MPLYt_b2D8HLA8KTJ-3",
    "lyrics": None,
    "source": None
}
```
Then it is much easier to process it from the code:
```python
result = ytMusic.get_lyrics("0Ie6OIvq33E")
if result["lyrics"] is not None:
    print(result["lyrics"])
else:
    print("Lyrics not available")
```

**Comment by alexmercerind** [comment]
@raitonoberu, a more elegant approach can be to add another boolean key like "lyricsFound" to the resulting dictionary. By this, we'll be able to get both default strings from YouTube & a way to differentiate aswell.
```json
{
    "videoId": "0Ie6OIvq33E",
    "browseId": "MPLYt_b2D8HLA8KTJ-3",
    "lyricsFound": false,
    "lyrics": "If the song has lyrics, they'll show up here when they become available",
    "source": "Lyrics not available"
}
```

@sigma67 What do you think about the two ideas? Or do you have something else in mind?

**Comment by alexmercerind** [comment]
Now things are fine from all the point of views.
```py
from json import dumps
from ytmusicapi import YTMusic
with YTMusic() as ytMusic:
    result = ytMusic.get_lyrics('LFJIxKC1tBc')
    print(dumps(result, indent = 4))
    result = ytMusic.get_lyrics('0Ie6OIvq33E')
    print(dumps(result, indent = 4))
```
Now this script gives following result in the terminal.
```json
{
    "videoId": "LFJIxKC1tBc",
    "browseId": "MPLYt_3qQDfDjDB7j-2",
    "lyricsFound": true,
    "lyrics": "Why's it so hard to look me in the eye?\r\nPlaying with that cross that's on your chain\r\nI know you only ever bite your lip\r\nWhen it's something you're afraid to say\r\n\r\nIs this the last time that I lay my eyes upon you?\r\nIs this the last time that I ever watch you leave?\r\nThis is the last thing I would ever have done to ya\r\nThis is the last thing that I thought you'd do to me\r\n\r\nWe said that it would last, but how come it's the last time?\r\nI'm tryna hold your hand but feeling like my hand's tied\r\nYou said we'd be forever, now you never ever be mine (oh-oh-oh)\r\nYou said that it would last, but how come it's the last time?\r\n\r\nYou practiced leaving many times before\r\nBut I guess you get it right today\r\nLeaving that ring I gave you in the drawer\r\nBut you taking every single part of me\r\n\r\nIs this the last time that I lay my eyes upon you?\r\nIs this the last time that I ever watch you leave?\r\nThis is the last thing I would ever have done to ya\r\nThis is the last thing that I thought you'd do to me\r\n\r\nWe said that it would last, but how come it's the last time? (Oh-oh-oh)\r\nI'm tryna hold your hand but feeling like my hand's tied (oh-oh-oh)\r\nYou said we'd be forever, now you never ever be mine (oh-oh-oh)\r\nYou said that it would last, but how come it's the last time? Oh (oh-oh-oh)\r\n\r\nI think of the first kiss \r\nThat lead to the first night\r\nWhoa, whoa\r\nI think of the first tiff\r\nThat lead to the first fight\r\nWhoa, whoa\r\nOoh\r\n\r\nYou said that it would last, but how come it's the last time?\r\nI'm tryna hold your hand but feeling like my hand's tied, mm (oh-oh-oh)\r\nWe always said we'd be forever, now you never ever be mine, ooh (oh-oh-oh)\r\nWe said that it would last, but how come it's the last time? Oh, ooh (oh-oh-oh)\r\n\r\nI think of the first kiss\r\nThat lead to the first night\r\nWhoa (first night), whoa (whoa)\r\nI think of the first tiff (the first tiff)\r\nThat lead to the first fight\r\nWhoa, whoa, oh\r\n\r\nYou said that it would last, but how come it's the last time?",
    "source": "Source: LyricFind"
}
{
    "videoId": "0Ie6OIvq33E",
    "browseId": "MPLYt_b2D8HLA8KTJ-3",
    "lyricsFound": false,
    "lyrics": "If the song has lyrics, they'll show up here when they become available",
    "source": "Lyrics not available"
}
```

Tests are also updated. Everything seems ready.

**Review by alexmercerind — COMMENTED** [review]
@sigma67 you may take a review now.

**Comment by sigma67** [comment]
Sorry for the delay, December is quite the busy month due to upcoming Christmas holidays. 

Finally had time to look at this in detail and improved some things:

- `next` endpoint is already used by `get_watch_playlist`, so I moved the browseId retrieval there
- the Lyrics key you use to find the correct tab is subject to localization, so I use a simple index for now. I'm not aware of any case where there is a different amount of tabs. If this changes in the future we can re-implement the loop with localization added

I apologize for the substantial changes, but I really dislike multiple API requests in a single function call (as you may have noticed on previous issues). These changes avoid that and provide additional data to the caller in case the watch playlist is also needed. There is still the cost of a breaking change to get_watch_playlist, but I'm willing to take that cost if it improves the transparency of the underlying web requests,

**Comment by alexmercerind** [comment]
Hello @sigma67!

You don't need to feel sorry for the delay, we are already glad for the work you have done for the community by spending your spare time. 😄
Thanks for merging this PR. 💜
I'll take care of the things you said next time (if I make one 😅).

Thanks for this awesome project.

**Pull request merged**
