### PR TITLE
Fix wrong or missing year in album search

### PR DESCRIPTION
**Pull request by alexmercerind**
With the following script.
```py
from ytmusicapi import YTMusic

with YTMusic() as music:
    music.search('Liam Payne', 'albums')
```

Printing ```search_result['year']``` from the same line (to which, the change is made), before this commit:
```
2019
2018
Dixie D’Amelio
Liam Payne
2017
2019
2019
Liam Payne
Liam Payne
Liam Payne
J. Balvin
2017
Liam Payne
2017
2019
Liam Payne
London On Da Track
Liam Payne
Cheat Codes
2018
```

After the change:

```
2019
2018
2020
2017
2017
2019
2019
2018
2018
2018
2018
2017
2017
2017
2019
2018
2017
2020
2020
2018
```

### CODE REVIEW

**Comment by sigma67** [comment]
Thanks for pointing out this problem. The PR unfortunately doesn't fix it for all search terms (i.e. the test search "Oasis Wonderwall" produces some wrong years).

We should probably switch to regex parsing like for songs and videos.

**Comment by sigma67** [comment]
It seems quite easy to fix actually, we can just reuse the code for songs and videos. Will push the fix shortly.

**Comment by alexmercerind** [comment]
Thankyou for taking care of this issue.

**Comment by sigma67** [comment]
Of course! Please check with 23f278c. Should also greatly improve the artist results for albums

**Pull request closed without merging**
